### ISSUE TITLE
source file for the .stl file

### ISSUE THREAD

**Issue by roblatour** [mudmin/AnotherMaker#8]
For the mounting 3D print for the Olimex ESP32 POE ISO board (  https://github.com/mudmin/AnotherMaker/blob/master/olimex/Olimex%20ESP32-POE-ISO/board_holder-65mm.stl  ) what was the .stl file designed in?   Can the source (for example .f3d file) for it be made available?

**Comment by Noschvie** [comment]
Same question for me, to be ordered within the EU, thanks!

**Comment by mudmin** [comment]
https://github.com/mudmin/AnotherMaker/blob/master/olimex/Olimex%20ESP32-POE-ISO/holder.f3d

Here you go!

**Comment by roblatour** [comment]
Thank you!
